---
external_components:
  - source: github://tanishqmanuja/esphome-components
    components: [ ddp ]
    refresh: always
  # - source:
  #     type: local
  #     path: components
  #   components: [ ddp ]


ddp:

light:
  - id: !extend ${ light_id | default("led_strip") }
    effects:
      - ddp:
  