WIFI_SSID: ""
WIFI_PASSWORD: ""

ROUTER_GATEWAY: ""

# API Component docs: https://esphome.io/components/api.html
ESPHOME_API_ENC_KEY: ""

# Wifi Component docs: https://esphome.io/components/wifi.html
ESPHOME_FALLBACK_AP_PASSWORD: ""
