substitutions:
  IP: 192.168.29.66
  DEVICE_NAME: rfplug01
  FRIENDLY_NAME: RF Plug 01

packages:
  base: !include ./common/base.yaml
  board: !include ./common/board/esp32dev.yaml
  wifi.stable: !include ./common/wifi/stable.yaml
  sensor.status: !include ./common/sensor/status.yaml

preferences:
  flash_write_interval: 5s

remote_receiver:
  id: rf_receiver
  pin:
    number: GPIO4
    mode:
      input: true
      pullup: true
    inverted: true
  tolerance: 50%
  filter: 100us
  idle: 4ms

binary_sensor:
  - &rf_signal
    platform: remote_receiver
    id: signal_plug_1
    rc_switch_raw:
      protocol: 6
      code: '010001110011111000101001'
    filters:
      - settle: 250ms
    on_press:
      - switch.toggle: plug_1

  - <<: *rf_signal
    id: signal_plug_2
    rc_switch_raw:
      protocol: 6
      code: '011111010000010100011101'
    on_press:
      - switch.toggle: plug_2

  - <<: *rf_signal
    id: signal_plug_3
    rc_switch_raw:
      protocol: 6
      code: '010111000010010000111100'
    on_press:
      - switch.toggle: plug_3

  - <<: *rf_signal
    id: signal_plug_4
    rc_switch_raw:
      protocol: 6
      code: '011110100000000000011000'
    on_press:
      - switch.toggle: plug_4

  - <<: *rf_signal
    id: signal_all_on 
    rc_switch_raw:
      protocol: 6
      code: '011111110000011100011110'
    on_press:
      - switch.turn_on: plug_1
      - switch.turn_on: plug_2
      - switch.turn_on: plug_3
      - switch.turn_on: plug_4

  - <<: *rf_signal
    id: signal_all_off
    rc_switch_raw:
      protocol: 6
      code: '011100100000100000010100'
    on_press:
      - switch.turn_off: plug_1
      - switch.turn_off: plug_2
      - switch.turn_off: plug_3
      - switch.turn_off: plug_4

switch:
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode:
        output: true
        pullup: true
    id: plug_1
    name: Plug 1
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: GPIO33
      inverted: true
      mode:
        output: true
        pullup: true
    id: plug_2
    name: Plug 2
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: GPIO27
      inverted: true
      mode:
        output: true
        pullup: true
    id: plug_3
    name: Plug 3
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin:
      number: GPIO26
      inverted: true
      mode:
        output: true
        pullup: true
    id: plug_4
    name: Plug 4
    restore_mode: RESTORE_DEFAULT_OFF
